./configure Simplify figuring out the buildsystem
- Check exit codes directly. Fixes SC2181 errors
- Use `command(1)` instead of non-portable `which`. Fixes SC2230

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -159,64 +159,45 @@ fi
 
 if [ "$FETCH_ONLY" = "yes" ]; then exit 0; fi
 
-if [ ! -x "$(which cmake 2>/dev/null)" ]
+! command -v cmake >/dev/null && echo "-!- CMake required." >&2 && exit 1
+
+ninja_bin=$(command -v ninja-build)
+[ -z "$ninja_bin" ] && ninja_bin=$(command -v ninja)
+
+if [ -n "$ninja_bin" ] && ninja_version=$("$ninja_bin" --version 2>/dev/null);
 then
-    echo "-!- CMake required."
-    exit 1
+    echo "-- Found Ninja: $ninja_bin (found version \"$ninja_version\")"
+    cmake_type="Ninja"
+    exec_bin="$ninja_bin"
+    exec_command="$exec_bin"
+elif [ "/usr/sbin/ninja" = "$ninja_bin" ]; then
+    echo "-- Ninja at $ninja_bin is not usable. Did you install 'ninja' instead of 'ninja-build'?"
+elif make_bin=$(command -v make); then
+    echo "-- Found Make: $make_bin"
+    cmake_type="Unix Makefiles"
+    exec_bin="$make_bin"
+    exec_command="$exec_bin"
+    echo "--   Running with make. Using Ninja (ninja-build) might improve build experience."
 fi
 
-ninja_bin="$(which ninja-build 2>/dev/null)"
-if ! [ -x "$ninja_bin" ]; then
-    ninja_bin="$(which ninja 2>/dev/null)"
-fi
-if [ -x "$ninja_bin" ]; then
-    ninja_version=$($ninja_bin --version 2>/dev/null)
-    if [ $? -eq 0 ]; then
-        echo "-- Found Ninja: $ninja_bin (found version \"$ninja_version\")"
-        cmake_type="Ninja"
-        exec_bin="$ninja_bin"
-        exec_command="$exec_bin"
-    elif [ "/usr/sbin/ninja" = "$ninja_bin" ]; then
-        echo "-- Ninja at $ninja_bin is not usable. Did you install 'ninja' instead of 'ninja-build'?"
-    fi
-fi
-
-if ! [ -x "$exec_bin" ]; then
-    make_bin="$(which make 2>/dev/null)"
-    if [ -x "$make_bin" ]; then
-        echo "-- Found Make: $make_bin"
-        cmake_type="Unix Makefiles"
-        exec_bin="$make_bin"
-        exec_command="$exec_bin"
-        echo "--   Running with make. Using Ninja (ninja-build) might improve build experience."
-    fi
-fi
-
-if ! [ -x "$exec_bin" ]; then
-    echo "-!- No compatible build system (Ninja, Make) found."
-    exit 4
-fi
+[ -z "$exec_bin" ] && echo "-!- No compatible build system (Ninja, Make) found." && exit 4
 
 
 if [ -f ./build ]
 then
     echo "-!- ./build file exists. ./configure can't continue"
     exit 2
-fi
-
-if [ -d build ]
+elif [ -d build ]
 then
-    last_type=`cat build/.cmake_type`
-    if [ "$cmake_type" != "$last_type" ]
+    if [ "$cmake_type" != "$(cat build/.cmake_type)" ]
     then
         echo "-- Using different build system, cleaning build system files"
-        cd build
-        rm -r CMakeCache.txt CMakeFiles
-        cd ..
+        rm -r ./build/CMakeCache.txt ./build/CMakeFiles
     fi
+else
+    mkdir build
 fi
 
-mkdir -p build
 cd build
 
 echo "$cmake_type" > .cmake_type
